name: CI laravel-ovh

on:
  - push
  - pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: true
      matrix:
        include:
          - php: '8.1'
            illuminate: '10.*'
          - php: '8.2'
            illuminate: '10.*'
          - php: '8.2'
            illuminate: '11.*'
          - php: '8.2'
            illuminate: '12.*'
          - php: '8.3'
            illuminate: '11.*'
          - php: '8.3'
            illuminate: '12.*'
          - php: '8.3'
            illuminate: '13.*'
          - php: '8.4'
            illuminate: '12.*'
          - php: '8.4'
            illuminate: '13.*'

    name: P${{ matrix.php }} - L${{ matrix.illuminate }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect Composer Cache Directory
        id: composer-cache
        run: echo "dir=$(composer config cache-files-dir)" >> "$GITHUB_OUTPUT"

      - name: Setup Composer Cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: dependencies-illuminate-${{ matrix.illuminate }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          coverage: none

      - name: Install Composer Packages
        run: |
          composer require "illuminate/support:${{ matrix.illuminate }}" --no-interaction --no-update
          composer update --prefer-stable --prefer-dist --no-interaction

      - name: Execute PHP Linter
        run: composer test:lint

      - name: Execute PHPUnit Tests
        run: composer test:unit
